"""Record which SMART launch an encounter was created under.

TASK-052b fills ``insurance_payer``, ``insurance_plan_type`` and ``state`` from
the EHR, and the credential that lets it read the EHR is named by a
``launch_id`` — the key that ``fhir-integration`` stores an access token under.
Nothing on ``encounters`` recorded which launch a visit came from, so the
population had no way to reach the token.

**The mapping is explicit and is never an equality.** A SMART launch and an
encounter session are two different things with two different lifetimes: the
launch precedes the visit, one launch can outlive several encounters, and at
callback time no encounter exists to key a token on. See CLAUDE.md, "A SMART
launch is not an encounter session". This column is that recorded mapping, which
is the whole point — assuming ``launch_id == session_id`` is the failure the
section exists to prevent, and a column is what makes the assumption
unnecessary.

Nullable, because an encounter can be started without a SMART launch behind it:
``POST /sessions/start`` accepts a body with no ``launch_id`` and every existing
row predates this column. A NOT NULL would mean inventing a launch for those.

``VARCHAR(64)`` rather than ``UUID``: ``launch_id`` is generated by
``fhir-integration`` as a UUID string today, but it names an identifier that
service owns, and a column typed ``UUID`` would make a future opaque handle a
migration rather than a change in one place.

Revision ID: 0006_encounter_launch_id
Revises: 0005_one_nudge_per_procedure
Create Date: 2026-08-31
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_encounter_launch_id"
down_revision: str | None = "0005_one_nudge_per_procedure"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the nullable launch_id column."""
    # No column comment, for the reason given in 0002: nothing else in this
    # schema carries one and the drift guard compares them.
    op.add_column("encounters", sa.Column("launch_id", sa.String(64), nullable=True))


def downgrade() -> None:
    """Drop the column."""
    op.drop_column("encounters", "launch_id")
